bin_PROGRAMS = frmw_aligncons

frmw_aligncons_SOURCES = main.cpp \
	Clustal.cpp \
	Clustal.h \
	clustalw_version.h \
	Help.cpp \
	Help.h \
	alignment/Alignment.cpp \
	alignment/Alignment.h \
	alignment/AlignmentOutput.cpp \
	alignment/AlignmentOutput.h \
	alignment/Sequence.cpp \
	alignment/Sequence.h \
	consistency/Constraints.cpp \
	consistency/Constraints.h \
	consistency/ConstrEntry.cpp \
	consistency/ConstrEntry.h \
	consistency/Edge.cpp \
	consistency/Edge.h \
	consistency/TCoffeeConsistency.cpp \
	consistency/TCoffeeConsistency.h \
	fileInput/ClustalFileParser.cpp \
	fileInput/ClustalFileParser.h \
	fileInput/EMBLFileParser.cpp \
	fileInput/EMBLFileParser.h \
	fileInput/FileParser.cpp \
	fileInput/FileParser.h \
	fileInput/FileReader.cpp \
	fileInput/FileReader.h \
	fileInput/GDEFileParser.cpp \
	fileInput/GDEFileParser.h \
	fileInput/InFileStream.cpp \
	fileInput/InFileStream.h \
	fileInput/MSFFileParser.cpp \
	fileInput/MSFFileParser.h \
	fileInput/PearsonFileParser.cpp \
	fileInput/PearsonFileParser.h \
	fileInput/PIRFileParser.cpp \
	fileInput/PIRFileParser.h \
	fileInput/RSFFileParser.cpp \
	fileInput/RSFFileParser.h \
	general/Array2D.h \
	general/ClustalWResources.cpp \
	general/ClustalWResources.h \
	general/clustalw.h \
	general/DebugLog.cpp \
	general/DebugLog.h \
	general/debuglogObject.h \
	general/general.h \
	general/InvalidCombination.cpp \
	general/OutputFile.cpp \
	general/OutputFile.h \
	general/SequenceNotFoundException.h \
	general/SquareMat.h \
	general/Stats.cpp \
	general/Stats.h \
	general/statsObject.h \
	general/SymMatrix.h \
	general/userparams.h \
	general/UserParameters.cpp \
	general/UserParameters.h \
	general/Utility.cpp \
	general/Utility.h \
	general/utils.h \
	general/VectorOutOfRange.cpp \
	general/VectorOutOfRange.h \
	general/general/VectorUtility.h \
	interface/CommandLineParser.cpp \
	interface/CommandLineParser.h \
	multipleAlign/MSA.cpp \
	multipleAlign/MSA.h \
	multipleAlign/MyersMillerProfileAlign.cpp \
	multipleAlign/MyersMillerProfileAlign.h \
	multipleAlign/ProfileAlignAlgorithm.h \
	multipleAlign/ProfileBase.cpp \
	multipleAlign/ProfileBase.h \
	multipleAlign/ProfileWithSub.cpp \
	multipleAlign/ProfileWithSub.h \
	multipleAlign/ProfileStandard.cpp \
	multipleAlign/ProfileStandard.h \
	substitutionMatrix/globalmatrix.h \
	substitutionMatrix/matrices.h \
	substitutionMatrix/SubMatrix.cpp \
	substitutionMatrix/SubMatrix.h \
	tree/AlignmentSteps.cpp \
	tree/AlignmentSteps.h \
	tree/ClusterTreeAlgorithm.h \
	tree/ClusterTree.cpp \
	tree/ClusterTree.h \
	tree/ClusterTreeOutput.cpp \
	tree/ClusterTreeOutput.h \
	tree/dayhoff.h \
	tree/RandomGenerator.cpp \
	tree/RandomGenerator.h \
	tree/Tree.cpp \
	tree/Tree.h \
	tree/TreeInterface.cpp \
	tree/TreeInterface.h \
	tree/UPGMA/Node.cpp \
	tree/UPGMA/Node.h \
	tree/UPGMA/RootedClusterTree.cpp \
	tree/UPGMA/RootedClusterTree.h \
	tree/UPGMA/RootedGuideTree.cpp \
	tree/UPGMA/RootedGuideTree.h \
	tree/UPGMA/RootedTreeOutput.cpp \
	tree/UPGMA/RootedTreeOutput.h \
	tree/UPGMA/UPGMAAlgorithm.cpp \
	tree/UPGMA/UPGMAAlgorithm.h \
	tree/UPGMA/upgmadata.h

