bin_PROGRAMS = frmw_kmers

frmw_kmers_SOURCES = main.cpp \
	Clustal.cpp \
	Clustal.h \
	clustalw_version.h \
	Help.cpp \
	Help.h \
	alignment/Alignment.cpp \
	alignment/Alignment.h \
	alignment/AlignmentOutput.cpp \
	alignment/AlignmentOutput.h \
	alignment/Sequence.cpp \
	alignment/Sequence.h \
	fileInput/ClustalFileParser.cpp \
	fileInput/ClustalFileParser.h \
	fileInput/EMBLFileParser.cpp \
	fileInput/EMBLFileParser.h \
	fileInput/FileParser.cpp \
	fileInput/FileParser.h \
	fileInput/FileReader.cpp \
	fileInput/FileReader.h \
	fileInput/GDEFileParser.cpp \
	fileInput/GDEFileParser.h \
	fileInput/InFileStream.cpp \
	fileInput/InFileStream.h \
	fileInput/MSFFileParser.cpp \
	fileInput/MSFFileParser.h \
	fileInput/PearsonFileParser.cpp \
	fileInput/PearsonFileParser.h \
	fileInput/PIRFileParser.cpp \
	fileInput/PIRFileParser.h \
	fileInput/RSFFileParser.cpp \
	fileInput/RSFFileParser.h \
	general/Array2D.h \
	general/ClustalWResources.cpp \
	general/ClustalWResources.h \
	general/clustalw.h \
	general/DebugLog.cpp \
	general/DebugLog.h \
	general/debuglogObject.h \
	general/general.h \
	general/InvalidCombination.cpp \
	general/SequenceNotFoundException.h \
	general/SquareMat.h \
	general/Stats.cpp \
	general/Stats.h \
	general/statsObject.h \
	general/SymMatrix.h \
	general/userparams.h \
	general/UserParameters.cpp \
	general/UserParameters.h \
	general/Utility.cpp \
	general/Utility.h \
	general/utils.h \
	general/VectorOutOfRange.cpp \
	general/VectorOutOfRange.h \
	interface/CommandLineParser.cpp \
	interface/CommandLineParser.h \
	pairwise/KmersPairwiseAlign.cpp \
	pairwise/KmersPairwiseAlign.h \
	pairwise/PairwiseAlignBase.h \
	substitutionMatrix/globalmatrix.h \
	substitutionMatrix/matrices.h \
	substitutionMatrix/SubMatrix.cpp \
	substitutionMatrix/SubMatrix.h

